### ISSUE TITLE
Publish latest package.json to npm

### ISSUE THREAD

**Issue by EliSnow** [kristw/ng-vega#1]
The latest version of ng-vega published on npm has a dependency on Vega "~1.5.0". That version of Vega seemed to either require the use of node-gyp or had a dependency which did. For those of us who don't want to install Python 2 (and any other native module build dependenies) in order to get ng-vega through npm, it would be great if you could publish you latest package.json to npm.

**Comment by kristw** [comment]
Done! v1.2.0 published.
